function C = perform_cost_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HEUR
%    C = PERFORM_COST_HEUR(W_F,W_J,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Mar-2021 00:00:53

W_t = W(1);
W_f = W(2);
W_j = W(3);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = rx.^2;
t3 = ry.^2;
t4 = rz.^2;
t5 = 1.0./ka;
t6 = 1.0./kc;
t7 = t2+t3+t4;
t8 = 1.0./sqrt(t7);
C = W_t.*(alpha.*t5.*(1.3e+1./2.0)+b.^2.*t6+t6./t8)+W_f.*(kc+(ka.*pi)./2.0+sqrt((vx+kc.*rx.*t8).^2+(vy+kc.*ry.*t8).^2+(vz+kc.*rz.*t8).^2)+alpha.^2.*t5.*wandamax.*(1.3e+1./2.0)+alpha.*wmax.*pi)+(W_j.*1.0./t6.^2)./b;
