function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_J,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Mar-2021 19:50:23

W_t = W(1);
W_f = W(2);
W_j = W(3);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = rx.^2;
t3 = ry.^2;
t4 = rz.^2;
t5 = 1.0./b.^2;
t6 = 1.0./ka.^3;
t7 = 1.0./kc.^2;
t8 = 1.0./kc.^3;
t9 = W_j.*kc.*t5.*2.0;
t10 = W_t.*b.*t7.*2.0;
t13 = t2+t3+t4;
t11 = -t9;
t12 = -t10;
t14 = 1.0./t13;
t15 = 1.0./sqrt(t13);
t16 = kc.*rx.*t15;
t17 = kc.*ry.*t15;
t18 = kc.*rz.*t15;
t19 = t11+t12;
t20 = t16+vx;
t21 = t17+vy;
t22 = t18+vz;
t23 = t20.^2;
t24 = t21.^2;
t25 = t22.^2;
t26 = t23+t24+t25;
d2Cdp2_heur = reshape([(W_t.*2.0)./kc+(W_j.*1.0./b.^3.*2.0)./t7,t19,0.0,t19,W_t.*((t8.*2.0)./t5+(t8.*2.0)./t15)+(W_j.*2.0)./b-W_f.*((1.0./t26.^(3.0./2.0).*(rx.*t15.*t20.*2.0+ry.*t15.*t21.*2.0+rz.*t15.*t22.*2.0).^2)./4.0-(1.0./sqrt(t26).*(t2.*t14.*2.0+t3.*t14.*2.0+t4.*t14.*2.0))./2.0),0.0,0.0,0.0,W_t.*alpha.*t6.*1.3e+1+W_f.*alpha.^2.*t6.*wandamax.*9.191],[3,3]);
