function F_est = F_heur(alpha,ka,kc,r,v,wandamax,wmax)
%F_HEUR
%    F_EST = F_HEUR(ALPHA,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Aug-2021 17:55:39

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.^2;
t4 = ka.^2;
t5 = rx.^2;
t6 = ry.^2;
t7 = rz.^2;
t3 = t2.^2;
t8 = t5+t6+t7;
t9 = 1.0./sqrt(t8);
F_est = kc+ka.*pi+wandamax.*sqrt(t3./t4+1.0./kc.^4.*t3.*(ka+t4+alpha.*wmax.*2.0+(t2.*wmax.^2)./ka+1.0).^2).*1.3e+1+sqrt((vx+kc.*rx.*t9).^2+(vy+kc.*ry.*t9).^2+(vz+kc.*rz.*t9).^2)+wmax.*pi.*sqrt(t2+1.0./kc.^2.*t2.*(ka+t4./4.0+alpha.*wmax+1.0./4.0).^2).*2.0;
