function C = perform_cost_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HEUR
%    C = PERFORM_COST_HEUR(W_F,W_J,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Aug-2021 17:55:29

W_t = W(1);
W_f = W(2);
W_j = W(3);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.^2;
t4 = ka.^2;
t5 = rx.^2;
t6 = ry.^2;
t7 = rz.^2;
t8 = 1.0./ka;
t9 = 1.0./kc;
t3 = t2.^2;
t10 = t5+t6+t7;
t11 = 1.0./sqrt(t10);
C = W_f.*(kc+ka.*pi+sqrt((vx+kc.*rx.*t11).^2+(vy+kc.*ry.*t11).^2+(vz+kc.*rz.*t11).^2)+wandamax.*sqrt(t3./t4+t3.*t9.^4.*(ka+t4+alpha.*wmax.*2.0+t2.*t8.*wmax.^2+1.0).^2).*1.3e+1+wmax.*pi.*sqrt(t2+t2.*t9.^2.*(ka+t4./4.0+alpha.*wmax+1.0./4.0).^2).*2.0)+W_t.*(alpha.*t8.*1.3e+1+b.^2.*t9+t9./t11)+(W_j.*1.0./t9.^2)./b;
