function d2amaxLVFdp2 = hess_p_amaxLVF(alphap,fact,theta_d,vmax)
%HESS_P_AMAXLVF
%    D2AMAXLVFDP2 = HESS_P_AMAXLVF(ALPHAP,FACT,THETA_D,VMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Mar-2021 00:45:03

t2 = theta_d.*2.0;
t3 = 1.0./alphap.^2;
t4 = 1.0./theta_d;
t5 = t2+pi;
t6 = fact.*t3.*t4.*t5.*vmax.*pi.*7.24612e-1;
t7 = -t6;
d2amaxLVFdp2 = reshape([1.0./alphap.^3.*fact.*t4.*t5.*vmax.^2.*pi.*7.24612e-1,t7,t7,(fact.*t4.*t5.*pi.*7.24612e-1)./alphap],[2,2]);
