function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 21:09:56

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

W_t = W(1);
W_f = W(2);

t2 = alpha.*wmax;
t3 = alpha.^2;
t5 = b+2.0;
t6 = b.^2;
t7 = ka.^2;
t8 = rx.^2;
t9 = ry.^2;
t10 = rz.^2;
t11 = wmax.^2;
t12 = 1.0./ka.^3;
t13 = 1.0./kc;
t18 = ka./2.0;
t4 = t3.^2;
t14 = t13.^2;
t15 = t13.^3;
t17 = t13.^5;
t19 = t18+1.0;
t20 = t7./4.0;
t24 = t8+t9+t10;
t16 = t14.^2;
t21 = ka.*t14.*2.0;
t22 = W_t.*t5.*t14;
t23 = t19.^2;
t26 = W_f.*b.*t11.*t14.*2.0;
t28 = 1.0./t24;
t29 = ka+t2+t20+1.0./4.0;
t30 = 1.0./sqrt(t24);
t25 = -t22;
t27 = -t26;
t31 = t29.^2;
t32 = t29.^3;
t33 = kc.*rx.*t30;
t34 = kc.*ry.*t30;
t35 = kc.*rz.*t30;
t36 = t33+vx;
t37 = t34+vy;
t38 = t35+vz;
t42 = t25+t27;
t43 = t3.*t14.*t31;
t39 = t36.^2;
t40 = t37.^2;
t41 = t38.^2;
t44 = t3+t43;
t45 = 1.0./sqrt(t44);
t48 = t39+t40+t41;
t46 = t45.^3;
t47 = alpha.*t2.*t15.*t19.*t29.*t45.*pi.*2.0;
t49 = alpha.^3.*t2.*t17.*t19.*t32.*t46.*pi;
t50 = -t49;
t51 = t21+t47+t50;
t52 = W_f.*t51;
t53 = -t52;
d2Cdp2_heur = reshape([W_t.*t13+W_f.*t11.*t13.*2.0,t42,0.0,t42,W_t.*((t15.*2.0)./t30+t15.*(b.*2.0+t6./2.0+1.0./2.0).*2.0)+W_f.*(1.0./t48.^(3.0./2.0).*(rx.*t30.*t36.*2.0+ry.*t30.*t37.*2.0+rz.*t30.*t38.*2.0).^2.*(-1.0./4.0)+t15.*(t7+t6.*t11+t2.*wmax).*2.0+(1.0./sqrt(t48).*(t8.*t28.*2.0+t9.*t28.*2.0+t10.*t28.*2.0))./2.0+alpha.*t2.*t16.*t31.*t45.*pi.*3.0-alpha.^3.*t2.*t14.^3.*t31.^2.*t46.*pi),t53,0.0,t53,W_f.*(t13.*2.0+t3.*t12.*wandamax.*1.3e+1+alpha.*t2.*t14.*t23.*t45.*pi+(alpha.*t2.*t14.*t29.*t45.*pi)./2.0-alpha.^3.*t2.*t16.*t23.*t31.*t46.*pi)+W_t.*alpha.*t12.*1.3e+1],[3,3]);
