function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_J,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Sep-2021 21:22:48

W_t = W(1);
W_f = W(2);
W_j = W(3);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.*wmax;
t3 = alpha.^2;
t5 = b+2.0;
t6 = b.^2;
t7 = ka.^2;
t8 = rx.^2;
t9 = ry.^2;
t10 = rz.^2;
t13 = 1.0./ka.^3;
t14 = 1.0./kc;
t19 = ka./2.0;
t4 = t3.^2;
t11 = 1.0./t3;
t12 = 1.0./t6;
t15 = t14.^2;
t16 = t14.^3;
t18 = t14.^5;
t20 = t19+1.0;
t21 = t7./4.0;
t26 = t8+t9+t10;
t17 = t15.^2;
t22 = W_j.*kc.*t12.*2.0;
t23 = W_t.*t5.*t15;
t24 = t20.^2;
t28 = W_f.*b.*t11.*t15.*2.0;
t29 = 1.0./t26;
t31 = ka+t2+t21+1.0./4.0;
t32 = 1.0./sqrt(t26);
t25 = -t22;
t27 = -t23;
t30 = -t28;
t33 = t31.^2;
t34 = t31.^3;
t35 = kc.*rx.*t32;
t36 = kc.*ry.*t32;
t37 = kc.*rz.*t32;
t38 = t35+vx;
t39 = t36+vy;
t40 = t37+vz;
t44 = t3.*t15.*t33;
t46 = t25+t27+t30;
t41 = t38.^2;
t42 = t39.^2;
t43 = t40.^2;
t45 = t3+t44;
t47 = 1.0./sqrt(t45);
t50 = t41+t42+t43;
t48 = t47.^3;
t49 = alpha.*t2.*t16.*t20.*t31.*t47.*pi.*4.0;
t51 = alpha.^3.*t2.*t18.*t20.*t34.*t48.*pi.*2.0;
t52 = -t51;
t53 = t49+t52;
t54 = W_f.*t53;
t55 = -t54;
d2Cdp2_heur = reshape([W_t.*t14+(W_j.*1.0./b.^3.*2.0)./t15+W_f.*t11.*t14.*2.0,t46,0.0,t46,W_f.*(1.0./t50.^(3.0./2.0).*(rx.*t32.*t38.*2.0+ry.*t32.*t39.*2.0+rz.*t32.*t40.*2.0).^2.*(-1.0./4.0)+(1.0./sqrt(t50).*(t8.*t29.*2.0+t9.*t29.*2.0+t10.*t29.*2.0))./2.0+t6.*t11.*t16.*2.0+alpha.*t2.*t17.*t33.*t47.*pi.*6.0-alpha.^3.*t2.*t15.^3.*t33.^2.*t48.*pi.*2.0)+(W_j.*2.0)./b+W_t.*((t16.*2.0)./t32+t16.*(b.*2.0+t6./2.0+1.0./2.0).*2.0),t55,0.0,t55,W_f.*(t3.*t13.*wandamax.*2.6e+1+alpha.*t2.*t15.*t24.*t47.*pi.*2.0+alpha.*t2.*t15.*t31.*t47.*pi-alpha.^3.*t2.*t17.*t24.*t33.*t48.*pi.*2.0)+W_t.*alpha.*t13.*1.3e+1],[3,3]);
