function F_est = F_heur(alpha,b,ka,kc,r,v,wandamax,wmax)
%F_HEUR
%    F_EST = F_HEUR(ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 19:58:39

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.^2;
t3 = ka.^2;
t4 = rx.^2;
t5 = ry.^2;
t6 = rz.^2;
t7 = 1.0./kc.^2;
t8 = t3./4.0;
t9 = t4+t5+t6;
t10 = ka+t8+1.0./4.0;
t12 = 1.0./sqrt(t9);
t11 = t10.^2;
t13 = t2.*t7.*t11;
t14 = t2+t13;
F_est = kc+(ka.*pi)./2.0+sqrt((vx+kc.*rx.*t12).^2+(vy+kc.*ry.*t12).^2+(vz+kc.*rz.*t12).^2)+(t14.*wandamax.*(1.3e+1./2.0))./ka+(wmax.^2.*(t2./2.0+alpha.*b+b.^2./2.0).*2.0)./kc+sqrt(t14).*wmax.*pi;
