function F_est = F_heur(alpha,b,ka,kc,r,v,wandamax,wmax)
%F_HEUR
%    F_EST = F_HEUR(ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 20:40:10

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);


t2 = alpha.^2;
t3 = rx.^2;
t4 = ry.^2;
t5 = rz.^2;
t6 = t3+t4+t5;
t7 = 1.0./sqrt(t6);
F_est = kc+(ka.*pi)./2.0+sqrt((vx+kc.*rx.*t7).^2+(vy+kc.*ry.*t7).^2+(vz+kc.*rz.*t7).^2)+(t2.*wandamax.*(1.3e+1./2.0))./ka+wmax.*pi.*sqrt(t2+1.0./kc.^2.*t2.*(ka+ka.^2./4.0+1.0./4.0).^2)+(wmax.^2.*(t2./2.0+alpha.*b+b.^2./2.0).*2.0)./kc;
