function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 20:40:09

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

W_t = W(1);
W_f = W(2);

t2 = alpha+b;
t3 = alpha.^2;
t5 = b+2.0;
t6 = b.^2;
t7 = ka.^2;
t8 = rx.^2;
t9 = ry.^2;
t10 = rz.^2;
t11 = wmax.^2;
t12 = 1.0./ka.^3;
t13 = 1.0./kc;
t18 = ka./2.0;
t4 = t3.^2;
t14 = t13.^2;
t15 = t13.^3;
t17 = t13.^5;
t19 = t6./2.0;
t20 = t18+1.0;
t21 = t7./4.0;
t24 = t8+t9+t10;
t16 = t14.^2;
t22 = W_t.*t5.*t14;
t23 = t20.^2;
t26 = ka+t21+1.0./4.0;
t27 = 1.0./t24;
t28 = W_f.*t2.*t11.*t14.*2.0;
t32 = 1.0./sqrt(t24);
t25 = -t22;
t29 = t26.^2;
t30 = t26.^3;
t31 = -t28;
t33 = kc.*rx.*t32;
t34 = kc.*ry.*t32;
t35 = kc.*rz.*t32;
t36 = t33+vx;
t37 = t34+vy;
t38 = t35+vz;
t39 = t3.*t14.*t29;
t43 = t25+t31;
t40 = t36.^2;
t41 = t37.^2;
t42 = t38.^2;
t44 = t3+t39;
t45 = 1.0./sqrt(t44);
t50 = t40+t41+t42;
t46 = t45.^3;
t47 = t3.*t15.*t20.*t26.*t45.*wmax.*pi.*2.0;
t48 = t4.*t17.*t20.*t30.*t46.*wmax.*pi;
t49 = -t48;
t51 = t47+t49;
t52 = W_f.*t51;
t53 = -t52;
d2Cdp2_heur = reshape([W_t.*t13+W_f.*t11.*t13.*2.0,t43,0.0,t43,W_t.*(t15.*(b.*2.0+t19+1.0./2.0).*2.0-t15.*(alpha-1.0./t32).*2.0)+W_f.*(1.0./t50.^(3.0./2.0).*(rx.*t32.*t36.*2.0+ry.*t32.*t37.*2.0+rz.*t32.*t38.*2.0).^2.*(-1.0./4.0)+(1.0./sqrt(t50).*(t8.*t27.*2.0+t9.*t27.*2.0+t10.*t27.*2.0))./2.0+t11.*t15.*(t3./2.0+t19+alpha.*b).*4.0-t4.*t14.^3.*t29.^2.*t46.*wmax.*pi+t3.*t16.*t29.*t45.*wmax.*pi.*3.0),t53,0.0,t53,W_f.*(t3.*t12.*wandamax.*1.3e+1+t3.*t14.*t23.*t45.*wmax.*pi+(t3.*t14.*t26.*t45.*wmax.*pi)./2.0-t4.*t16.*t23.*t29.*t46.*wmax.*pi)+W_t.*alpha.*t12.*1.3e+1],[3,3]);
