function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 19:58:38

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

W_t = W(1);
W_f = W(2);

t2 = alpha+b;
t3 = alpha.^2;
t5 = b+2.0;
t6 = b.^2;
t7 = ka.^2;
t8 = rx.^2;
t9 = ry.^2;
t10 = rz.^2;
t11 = wmax.^2;
t12 = 1.0./ka;
t15 = 1.0./kc;
t20 = ka./2.0;
t4 = t3.^2;
t13 = 1.0./t7;
t14 = t12.^3;
t16 = t15.^2;
t17 = t15.^3;
t19 = t15.^5;
t21 = t6./2.0;
t22 = t20+1.0;
t23 = t7./4.0;
t26 = t8+t9+t10;
t18 = t16.^2;
t24 = W_t.*t5.*t16;
t25 = t22.^2;
t28 = ka+t23+1.0./4.0;
t29 = 1.0./t26;
t30 = W_f.*t2.*t11.*t16.*2.0;
t34 = 1.0./sqrt(t26);
t27 = -t24;
t31 = t28.^2;
t32 = t28.^3;
t33 = -t30;
t35 = kc.*rx.*t34;
t36 = kc.*ry.*t34;
t37 = kc.*rz.*t34;
t50 = t3.*t12.*t17.*t22.*t28.*wandamax.*2.6e+1;
t38 = t35+vx;
t39 = t36+vy;
t40 = t37+vz;
t41 = t3.*t16.*t31;
t45 = t27+t33;
t47 = t3.*t13.*t17.*t31.*wandamax.*1.3e+1;
t51 = -t50;
t42 = t38.^2;
t43 = t39.^2;
t44 = t40.^2;
t46 = t3+t41;
t48 = 1.0./sqrt(t46);
t55 = t42+t43+t44;
t49 = t48.^3;
t52 = t3.*t17.*t22.*t28.*t48.*wmax.*pi.*2.0;
t53 = -t52;
t54 = t4.*t19.*t22.*t32.*t49.*wmax.*pi;
t56 = t47+t51+t53+t54;
t57 = W_f.*t56;
d2Cdp2_heur = reshape([W_t.*t15+W_f.*t11.*t15.*2.0,t45,0.0,t45,W_f.*(1.0./t55.^(3.0./2.0).*(rx.*t34.*t38.*2.0+ry.*t34.*t39.*2.0+rz.*t34.*t40.*2.0).^2.*(-1.0./4.0)+(1.0./sqrt(t55).*(t8.*t29.*2.0+t9.*t29.*2.0+t10.*t29.*2.0))./2.0+t11.*t17.*(t3./2.0+t21+alpha.*b).*4.0+t3.*t12.*t18.*t31.*wandamax.*3.9e+1-t4.*t16.^3.*t31.^2.*t49.*wmax.*pi+t3.*t18.*t31.*t48.*wmax.*pi.*3.0)+W_t.*(t17.*(b.*2.0+t21+1.0./2.0).*2.0-t17.*(alpha-1.0./t34).*2.0),t57,0.0,t57,W_f.*(t14.*t46.*wandamax.*1.3e+1+t3.*t12.*t16.*t25.*wandamax.*1.3e+1+t3.*t12.*t16.*t28.*wandamax.*(1.3e+1./2.0)-t3.*t13.*t16.*t22.*t28.*wandamax.*2.6e+1+t3.*t16.*t25.*t48.*wmax.*pi+(t3.*t16.*t28.*t48.*wmax.*pi)./2.0-t4.*t18.*t25.*t31.*t49.*wmax.*pi)+W_t.*alpha.*t14.*1.3e+1],[3,3]);
