function dCdp_heur = perform_cost_grad_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_GRAD_HEUR
%    DCDP_HEUR = PERFORM_COST_GRAD_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 20:40:08

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

W_t = W(1);
W_f = W(2);

t2 = alpha.^2;
t3 = b.^2;
t4 = ka.^2;
t5 = rx.^2;
t6 = ry.^2;
t7 = rz.^2;
t8 = wmax.^2;
t10 = 1.0./kc;
t9 = 1.0./t4;
t11 = t10.^2;
t12 = t3./2.0;
t13 = t4./4.0;
t14 = t5+t6+t7;
t15 = ka+t13+1.0./4.0;
t17 = 1.0./sqrt(t14);
t16 = t15.^2;
t18 = kc.*rx.*t17;
t19 = kc.*ry.*t17;
t20 = kc.*rz.*t17;
t21 = t18+vx;
t22 = t19+vy;
t23 = t20+vz;
t24 = t2.*t11.*t16;
t25 = t2+t24;
t26 = 1.0./sqrt(t25);
dCdp_heur = [W_t.*t10.*(b+2.0)+W_f.*t8.*t10.*(alpha+b).*2.0;-W_t.*(t11.*(b.*2.0+t12+1.0./2.0)-t11.*(alpha-1.0./t17))+W_f.*(((rx.*t17.*t21.*2.0+ry.*t17.*t22.*2.0+rz.*t17.*t23.*2.0).*1.0./sqrt(t21.^2+t22.^2+t23.^2))./2.0-t8.*t11.*(t2./2.0+t12+alpha.*b).*2.0-t2.*t10.^3.*t16.*t26.*wmax.*pi+1.0);W_f.*(pi./2.0-t2.*t9.*wandamax.*(1.3e+1./2.0)+t2.*t11.*t15.*t26.*wmax.*pi.*(ka./2.0+1.0))-W_t.*alpha.*t9.*(1.3e+1./2.0)];
