function C = perform_cost_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HEUR
%    C = PERFORM_COST_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 19:58:36

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

W_t = W(1);
W_f = W(2);

t2 = alpha.^2;
t3 = b.^2;
t4 = ka.^2;
t5 = rx.^2;
t6 = ry.^2;
t7 = rz.^2;
t8 = 1.0./ka;
t9 = 1.0./kc;
t10 = t9.^2;
t11 = t3./2.0;
t12 = t4./4.0;
t13 = t5+t6+t7;
t14 = ka+t12+1.0./4.0;
t16 = 1.0./sqrt(t13);
t15 = t14.^2;
t17 = t2.*t10.*t15;
t18 = t2+t17;
C = W_f.*(kc+(ka.*pi)./2.0+sqrt((vx+kc.*rx.*t16).^2+(vy+kc.*ry.*t16).^2+(vz+kc.*rz.*t16).^2)+t9.*wmax.^2.*(t2./2.0+t11+alpha.*b).*2.0+t8.*t18.*wandamax.*(1.3e+1./2.0)+sqrt(t18).*wmax.*pi)+W_t.*(alpha.*t8.*(1.3e+1./2.0)+t9.*(b.*2.0+t11+1.0./2.0)-t9.*(alpha-1.0./t16));
