function C = perform_cost_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HEUR
%    C = PERFORM_COST_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 20:40:07

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

W_t = W(1);
W_f = W(2);

t2 = alpha.^2;
t3 = b.^2;
t4 = rx.^2;
t5 = ry.^2;
t6 = rz.^2;
t7 = 1.0./ka;
t8 = 1.0./kc;
t9 = t3./2.0;
t10 = t4+t5+t6;
t11 = 1.0./sqrt(t10);
C = W_t.*(alpha.*t7.*(1.3e+1./2.0)+t8.*(b.*2.0+t9+1.0./2.0)-t8.*(alpha-1.0./t11))+W_f.*(kc+(ka.*pi)./2.0+sqrt((vx+kc.*rx.*t11).^2+(vy+kc.*ry.*t11).^2+(vz+kc.*rz.*t11).^2)+wmax.*pi.*sqrt(t2+t2.*t8.^2.*(ka+1.0./t7.^2./4.0+1.0./4.0).^2)+t8.*wmax.^2.*(t2./2.0+t9+alpha.*b).*2.0+t2.*t7.*wandamax.*(1.3e+1./2.0));
