function dCdp_heur = perform_cost_grad_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_GRAD_HEUR
%    DCDP_HEUR = PERFORM_COST_GRAD_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Mar-2022 19:58:36

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

W_t = W(1);
W_f = W(2);

t2 = alpha.^2;
t3 = b.^2;
t4 = ka.^2;
t5 = rx.^2;
t6 = ry.^2;
t7 = rz.^2;
t8 = wmax.^2;
t9 = 1.0./ka;
t11 = 1.0./kc;
t14 = ka./2.0;
t10 = 1.0./t4;
t12 = t11.^2;
t13 = t11.^3;
t15 = t3./2.0;
t16 = t14+1.0;
t17 = t4./4.0;
t18 = t5+t6+t7;
t19 = ka+t17+1.0./4.0;
t21 = 1.0./sqrt(t18);
t20 = t19.^2;
t22 = kc.*rx.*t21;
t23 = kc.*ry.*t21;
t24 = kc.*rz.*t21;
t25 = t22+vx;
t26 = t23+vy;
t27 = t24+vz;
t28 = t2.*t12.*t20;
t29 = t2+t28;
t30 = 1.0./sqrt(t29);
dCdp_heur = [W_t.*t11.*(b+2.0)+W_f.*t8.*t11.*(alpha+b).*2.0;-W_t.*(t12.*(b.*2.0+t15+1.0./2.0)-t12.*(alpha-1.0./t21))-W_f.*((rx.*t21.*t25.*2.0+ry.*t21.*t26.*2.0+rz.*t21.*t27.*2.0).*1.0./sqrt(t25.^2+t26.^2+t27.^2).*(-1.0./2.0)+t8.*t12.*(t2./2.0+t15+alpha.*b).*2.0+t2.*t9.*t13.*t20.*wandamax.*1.3e+1+t2.*t13.*t20.*t30.*wmax.*pi-1.0);W_f.*(pi./2.0-t10.*t29.*wandamax.*(1.3e+1./2.0)+t2.*t9.*t12.*t16.*t19.*wandamax.*1.3e+1+t2.*t12.*t16.*t19.*t30.*wmax.*pi)-W_t.*alpha.*t10.*(1.3e+1./2.0)];
