function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Sep-2021 23:33:02

W_t = W(1);
W_f = W(2);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);
t2 = alpha.*wmax;
t3 = alpha.^2;
t5 = b+2.0;
t6 = b.^2;
t7 = ka.^2;
t8 = rx.^2;
t9 = ry.^2;
t10 = rz.^2;
t11 = 1.0./alpha;
t12 = 1.0./ka.^3;
t13 = 1.0./kc;
t18 = ka./2.0;
t4 = t3.^2;
t14 = t13.^2;
t15 = t13.^3;
t17 = t13.^5;
t19 = t18+1.0;
t20 = t7./4.0;
t23 = t8+t9+t10;
t16 = t14.^2;
t21 = W_t.*t5.*t14;
t22 = t19.^2;
t25 = W_f.*b.*t11.*t14.*wmax.*2.0;
t26 = 1.0./t23;
t28 = ka+t2+t20+1.0./4.0;
t29 = 1.0./sqrt(t23);
t24 = -t21;
t27 = -t25;
t30 = t28.^2;
t31 = t28.^3;
t32 = kc.*rx.*t29;
t33 = kc.*ry.*t29;
t34 = kc.*rz.*t29;
t35 = t32+vx;
t36 = t33+vy;
t37 = t34+vz;
t41 = t3.*t14.*t30;
t42 = t24+t27;
t38 = t35.^2;
t39 = t36.^2;
t40 = t37.^2;
t43 = t3+t41;
t44 = 1.0./sqrt(t43);
t47 = t38+t39+t40;
t45 = t44.^3;
t46 = alpha.*t2.*t15.*t19.*t28.*t44.*pi.*4.0;
t48 = t2.*1.0./t11.^3.*t17.*t19.*t31.*t45.*pi.*2.0;
t49 = -t48;
t50 = t46+t49;
t51 = W_f.*t50;
t52 = -t51;
d2Cdp2_heur = reshape([W_t.*t13+W_f.*t11.*t13.*wmax.*2.0,t42,0.0,t42,W_t.*((t15.*2.0)./t29+t15.*(b.*2.0+t6./2.0+1.0./2.0).*2.0)+W_f.*(1.0./t47.^(3.0./2.0).*(rx.*t29.*t35.*2.0+ry.*t29.*t36.*2.0+rz.*t29.*t37.*2.0).^2.*(-1.0./4.0)+(1.0./sqrt(t47).*(t8.*t26.*2.0+t9.*t26.*2.0+t10.*t26.*2.0))./2.0+t6.*t11.*t15.*wmax.*2.0-t2.*1.0./t11.^3.*t14.^3.*t30.^2.*t45.*pi.*2.0+alpha.*t2.*t16.*t30.*t44.*pi.*6.0),t52,0.0,t52,W_f.*(t3.*t12.*wandamax.*2.6e+1+alpha.*t2.*t14.*t22.*t44.*pi.*2.0+alpha.*t2.*t14.*t28.*t44.*pi-t2.*1.0./t11.^3.*t16.*t22.*t30.*t45.*pi.*2.0)+W_t.*alpha.*t12.*1.3e+1],[3,3]);
