function F_est = F_heur_LVF(alphap,dRotNorm,fa,vmax,wandamax,wmax)
%F_HEUR_LVF
%    F_EST = F_HEUR_LVF(ALPHAP,DROTNORM,FA,VMAX,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Mar-2021 16:26:46

t2 = 1.0./fa;
t3 = 1.0./vmax;
F_est = alphap.*t2.*(wmax.*pi.*(7.07e+2./5.0e+2)+dRotNorm.*t3.*5.87517+(fa.*vmax.*2.0)./alphap+alphap.*t2.*t3.*wandamax.*9.22635);
