function C = perform_cost_heur_LVF(W_f,W_t,alphap,dRotNorm,fa,vmax,wandamax,wmax)
%PERFORM_COST_HEUR_LVF
%    C = PERFORM_COST_HEUR_LVF(W_F,W_T,ALPHAP,DROTNORM,FA,VMAX,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Mar-2021 16:26:45

t2 = 1.0./fa;
t3 = 1.0./vmax;
C = W_t.*alphap.*t2.*t3.*(8.31e+2./1.0e+2)+W_f.*alphap.*t2.*(wmax.*pi.*(7.07e+2./5.0e+2)+dRotNorm.*t3.*5.87517+(fa.*vmax.*2.0)./alphap+alphap.*t2.*t3.*wandamax.*9.22635);
