function F_est = F_heur(alpha,ka,kc,r,v,wandamax,wmax)
%F_HEUR
%    F_EST = F_HEUR(ALPHA,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Mar-2021 00:00:56

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = rx.^2;
t3 = ry.^2;
t4 = rz.^2;
t5 = t2+t3+t4;
t6 = 1.0./sqrt(t5);
F_est = kc+(ka.*pi)./2.0+sqrt((vx+kc.*rx.*t6).^2+(vy+kc.*ry.*t6).^2+(vz+kc.*rz.*t6).^2)+(alpha.^2.*wandamax.*(1.3e+1./2.0))./ka+alpha.*wmax.*pi;
