function dCdp_heur = perform_cost_grad_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_GRAD_HEUR
%    DCDP_HEUR = PERFORM_COST_GRAD_HEUR(W_F,W_J,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Aug-2021 17:55:31

W_t = W(1);
W_f = W(2);
W_j = W(3);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.*wmax;
t3 = alpha.^2;
t5 = ka.^2;
t6 = rx.^2;
t7 = ry.^2;
t8 = rz.^2;
t9 = wmax.^2;
t11 = 1.0./ka;
t13 = 1.0./kc.^2;
t4 = t3.^2;
t10 = t2.*2.0;
t12 = 1.0./t5;
t14 = t13.^2;
t15 = t5./4.0;
t17 = t6+t7+t8;
t18 = t2.^2.*t11;
t16 = t4.*t12;
t19 = ka+t2+t15+1.0./4.0;
t20 = 1.0./sqrt(t17);
t28 = ka+t5+t10+t18+1.0;
t21 = t19.^2;
t22 = kc.*rx.*t20;
t23 = kc.*ry.*t20;
t24 = kc.*rz.*t20;
t29 = t28.^2;
t25 = t22+vx;
t26 = t23+vy;
t27 = t24+vz;
t30 = t3.*t13.*t21;
t32 = t4.*t14.*t29;
t31 = t3+t30;
t34 = t16+t32;
t33 = 1.0./sqrt(t31);
t35 = 1.0./sqrt(t34);
dCdp_heur = [-(W_j.*1.0./b.^2)./t13+(W_t.*b.*2.0)./kc;-W_t.*(b.^2.*t13+t13./t20)+W_f.*(((rx.*t20.*t25.*2.0+ry.*t20.*t26.*2.0+rz.*t20.*t27.*2.0).*1.0./sqrt(t25.^2+t26.^2+t27.^2))./2.0-1.0./kc.^5.*t4.*t29.*t35.*wandamax.*2.6e+1-alpha.*1.0./kc.^3.*t2.*t21.*t33.*pi.*2.0+1.0)+(W_j.*kc.*2.0)./b;W_f.*(pi-t35.*wandamax.*(t4.*t11.^3.*2.0-t4.*t14.*t28.*(ka.*2.0-t2.^2.*t12+1.0).*2.0).*(1.3e+1./2.0)+alpha.*t10.*t13.*t19.*t33.*pi.*(ka./2.0+1.0))-W_t.*alpha.*t12.*1.3e+1];
