function F_est = F_heur(alpha,b,ka,kc,r,v,wandamax,wmax)
%F_HEUR
%    F_EST = F_HEUR(ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Sep-2021 17:57:08


rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.^2;
t3 = b.^2;
t4 = ka.^2;
t5 = rx.^2;
t6 = ry.^2;
t7 = rz.^2;
t8 = wmax.^2;
t9 = t4./4.0;
t10 = t5+t6+t7;
t11 = 1.0./sqrt(t10);
F_est = kc+(ka.*pi)./2.0+sqrt((vx+kc.*rx.*t11).^2+(vy+kc.*ry.*t11).^2+(vz+kc.*rz.*t11).^2)+(t2.*wandamax.*(1.3e+1./2.0))./ka+wmax.*pi.*sqrt(t2+1.0./kc.^2.*t2.*(ka+t9+alpha.*wmax+1.0./4.0).^2)+(pi.*(alpha.*t4.*4.0+b.^3.*t8+t2.*wmax.*(ka+t9+1.0./4.0).*8.0+alpha.*t3.*t8.*4.0+t2.*t8.*(b.*4.0+t3+1.0)).*(2.0./3.0))./(alpha.*kc);
