function dCdp_heur = perform_cost_grad_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_GRAD_HEUR
%    DCDP_HEUR = PERFORM_COST_GRAD_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Sep-2021 17:57:04

W_t = W(1);
W_f = W(2);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.*wmax;
t3 = alpha.^2;
t4 = b.*2.0;
t5 = b.^2;
t6 = ka.^2;
t7 = rx.^2;
t8 = ry.^2;
t9 = rz.^2;
t10 = wmax.^2;
t11 = 1.0./alpha;
t13 = 1.0./kc;
t15 = ka./2.0;
t12 = 1.0./t6;
t14 = t13.^2;
t16 = t15+1.0;
t17 = t6./4.0;
t18 = t7+t8+t9;
t19 = ka+t2+t17+1.0./4.0;
t20 = 1.0./sqrt(t18);
t21 = t19.^2;
t22 = kc.*rx.*t20;
t23 = kc.*ry.*t20;
t24 = kc.*rz.*t20;
t25 = t22+vx;
t26 = t23+vy;
t27 = t24+vz;
t28 = t3.*t14.*t21;
t29 = t3+t28;
t30 = 1.0./sqrt(t29);
dCdp_heur = [W_t.*t13.*(b+2.0)+W_f.*t11.*t13.*pi.*(t2.^2.*(t4+4.0)+t5.*t10.*3.0+b.*t2.*wmax.*8.0).*(2.0./3.0);-W_t.*(t14.*(t4+t5./2.0+1.0./2.0)+t14./t20)+W_f.*(((rx.*t20.*t25.*2.0+ry.*t20.*t26.*2.0+rz.*t20.*t27.*2.0).*1.0./sqrt(t25.^2+t26.^2+t27.^2))./2.0-t11.*t14.*pi.*(alpha.*t6.*4.0+b.^3.*t10+t2.^2.*(b.*4.0+t5+1.0)+alpha.*t2.*(ka+t17+1.0./4.0).*8.0+t2.*t5.*wmax.*4.0).*(2.0./3.0)-alpha.*t2.*t13.^3.*t21.*t30.*pi+1.0);W_f.*(pi./2.0-t3.*t12.*wandamax.*(1.3e+1./2.0)+t11.*t13.*pi.*(alpha.*ka.*8.0+alpha.*t2.*t16.*8.0).*(2.0./3.0)+alpha.*t2.*t14.*t16.*t19.*t30.*pi)-W_t.*alpha.*t12.*(1.3e+1./2.0)];
