function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    19-Sep-2021 17:57:08

W_t = W(1);
W_f = W(2);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = alpha.*wmax;
t3 = alpha.^2;
t5 = b.*2.0;
t6 = b+2.0;
t7 = b.^2;
t8 = ka.^2;
t9 = rx.^2;
t10 = ry.^2;
t11 = rz.^2;
t12 = wmax.^2;
t13 = 1.0./alpha;
t14 = 1.0./ka.^3;
t15 = 1.0./kc;
t21 = alpha.*ka.*8.0;
t22 = ka./2.0;
t4 = t3.^2;
t16 = t15.^2;
t17 = t15.^3;
t19 = t15.^5;
t20 = t5+4.0;
t23 = t22+1.0;
t24 = t8./4.0;
t25 = t7.*t12.*3.0;
t26 = b.*t2.*wmax.*8.0;
t29 = t9+t10+t11;
t18 = t16.^2;
t27 = W_t.*t6.*t16;
t28 = t23.^2;
t31 = t2.^2.*t20;
t32 = 1.0./t29;
t33 = alpha.*t2.*t23.*8.0;
t34 = ka+t2+t24+1.0./4.0;
t35 = 1.0./sqrt(t29);
t30 = -t27;
t36 = t34.^2;
t37 = t34.^3;
t38 = kc.*rx.*t35;
t39 = kc.*ry.*t35;
t40 = kc.*rz.*t35;
t44 = t21+t33;
t49 = t25+t26+t31;
t41 = t38+vx;
t42 = t39+vy;
t43 = t40+vz;
t48 = t3.*t16.*t36;
t51 = t13.*t16.*t44.*pi.*(2.0./3.0);
t54 = W_f.*t13.*t16.*t49.*pi.*(2.0./3.0);
t45 = t41.^2;
t46 = t42.^2;
t47 = t43.^2;
t50 = t3+t48;
t55 = -t54;
t52 = 1.0./sqrt(t50);
t56 = t30+t55;
t58 = t45+t46+t47;
t53 = t52.^3;
t57 = alpha.*t2.*t17.*t23.*t34.*t52.*pi.*2.0;
t59 = t2.*1.0./t13.^3.*t19.*t23.*t37.*t53.*pi;
t60 = -t59;
t61 = t51+t57+t60;
t62 = W_f.*t61;
t63 = -t62;
d2Cdp2_heur = reshape([W_t.*t15+W_f.*t13.*t15.*pi.*(b.*t12.*6.0+t2.*wmax.*8.0+t2.^2.*2.0).*(2.0./3.0),t56,0.0,t56,W_t.*(t17.*(t5+t7./2.0+1.0./2.0).*2.0+(t17.*2.0)./t35)+W_f.*(1.0./t58.^(3.0./2.0).*(rx.*t35.*t41.*2.0+ry.*t35.*t42.*2.0+rz.*t35.*t43.*2.0).^2.*(-1.0./4.0)+(1.0./sqrt(t58).*(t9.*t32.*2.0+t10.*t32.*2.0+t11.*t32.*2.0))./2.0+t13.*t17.*pi.*(alpha.*t8.*4.0+b.^3.*t12+t2.^2.*(b.*4.0+t7+1.0)+alpha.*t2.*(ka+t24+1.0./4.0).*8.0+t2.*t7.*wmax.*4.0).*(4.0./3.0)-t2.*1.0./t13.^3.*t16.^3.*t36.^2.*t53.*pi+alpha.*t2.*t18.*t36.*t52.*pi.*3.0),t63,0.0,t63,W_f.*(t3.*t14.*wandamax.*1.3e+1+t13.*t15.*pi.*(alpha.*8.0+alpha.*t2.*4.0).*(2.0./3.0)+alpha.*t2.*t16.*t28.*t52.*pi+(alpha.*t2.*t16.*t34.*t52.*pi)./2.0-t2.*1.0./t13.^3.*t18.*t28.*t36.*t53.*pi)+W_t.*alpha.*t14.*1.3e+1],[3,3]);
