function damaxCLVFdp = grad_p_amaxCLVF(alpha,b,ka,kc,wmax)
%GRAD_P_AMAXCLVF
%    DAMAXCLVFDP = GRAD_P_AMAXCLVF(ALPHA,B,KA,KC,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    22-Mar-2021 00:45:06

t2 = ka.^2;
t3 = kc.^2;
t4 = 1.0./alpha;
t5 = 1.0./b;
t6 = sqrt(3.0);
t7 = t2.*t4;
t8 = t3.*t5;
t10 = ka.*t6.*wmax.*(2.0./9.0);
t9 = t7./2.0;
t11 = t7+t8;
t12 = t11.^2;
t13 = t9+t10;
t14 = t13.^2;
t15 = t12+t14;
t16 = 1.0./sqrt(t15);
damaxCLVFdp = [-t5.*t8.*t11.*t16;kc.*t5.*t11.*t16.*2.0;(t16.*(t13.*(ka.*t4+t6.*wmax.*(2.0./9.0)).*2.0+ka.*t4.*t11.*4.0))./2.0+sqrt(7.0).*t6.*wmax.*(4.0./9.0)];
