function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_J,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-Aug-2021 21:42:35


W_t = W(1);
W_f = W(2);
W_j = W(3);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);


t2 = alpha.*wmax;
t3 = alpha.^2;
t5 = ka.^2;
t6 = rx.^2;
t7 = ry.^2;
t8 = rz.^2;
t9 = 1.0./b.^2;
t10 = 1.0./ka.^3;
t11 = 1.0./kc.^2;
t12 = 1.0./kc.^3;
t14 = 1.0./kc.^5;
t15 = ka./2.0;
t4 = t3.^2;
t13 = t11.^2;
t16 = t15+1.0;
t17 = t5./4.0;
t18 = W_j.*kc.*t9.*2.0;
t19 = W_t.*b.*t11.*2.0;
t23 = t6+t7+t8;
t20 = t16.^2;
t21 = -t18;
t22 = -t19;
t24 = 1.0./t23;
t25 = ka+t2+t17+1.0./4.0;
t26 = 1.0./sqrt(t23);
t27 = t25.^2;
t28 = t25.^3;
t29 = kc.*rx.*t26;
t30 = kc.*ry.*t26;
t31 = kc.*rz.*t26;
t32 = t21+t22;
t33 = t29+vx;
t34 = t30+vy;
t35 = t31+vz;
t39 = t3.*t11.*t27;
t36 = t33.^2;
t37 = t34.^2;
t38 = t35.^2;
t40 = t3+t39;
t41 = 1.0./sqrt(t40);
t44 = t36+t37+t38;
t42 = t41.^3;
t43 = alpha.*t2.*t12.*t16.*t25.*t41.*pi.*2.0;
t45 = alpha.^3.*t2.*t14.*t16.*t28.*t42.*pi;
t46 = -t45;
t47 = t43+t46;
t48 = W_f.*t47;
t49 = -t48;
d2Cdp2_heur = reshape([(W_t.*2.0)./kc+(W_j.*1.0./b.^3.*2.0)./t11,t32,0.0,t32,W_t.*((t12.*2.0)./t9+(t12.*2.0)./t26)+(W_j.*2.0)./b-W_f.*((1.0./t44.^(3.0./2.0).*(rx.*t26.*t33.*2.0+ry.*t26.*t34.*2.0+rz.*t26.*t35.*2.0).^2)./4.0-(1.0./sqrt(t44).*(t6.*t24.*2.0+t7.*t24.*2.0+t8.*t24.*2.0))./2.0-alpha.*t2.*t13.*t27.*t41.*pi.*3.0+alpha.^3.*t2.*t11.^3.*t27.^2.*t42.*pi),t49,0.0,t49,W_f.*(t3.*t10.*wandamax.*1.3e+1+alpha.*t2.*t11.*t20.*t41.*pi+(alpha.*t2.*t11.*t25.*t41.*pi)./2.0-alpha.^3.*t2.*t13.*t20.*t27.*t42.*pi)+W_t.*alpha.*t10.*1.3e+1],[3,3]);
