function dCdp_heur = perform_cost_grad_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_GRAD_HEUR
%    DCDP_HEUR = PERFORM_COST_GRAD_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Sep-2021 23:00:23

W_t = W(1);
W_f = W(2);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = exp(b);
t3 = alpha.*wmax;
t4 = alpha.^2;
t5 = ka.^2;
t6 = rx.^2;
t7 = ry.^2;
t8 = rz.^2;
t10 = 1.0./kc;
t9 = 1.0./t5;
t11 = t10.^2;
t12 = t5./4.0;
t13 = t6+t7+t8;
t14 = ka+t3+t12+1.0./4.0;
t15 = 1.0./sqrt(t13);
t16 = t14.^2;
t17 = kc.*rx.*t15;
t18 = kc.*ry.*t15;
t19 = kc.*rz.*t15;
t20 = t17+vx;
t21 = t18+vy;
t22 = t19+vz;
t23 = t4.*t11.*t16;
t24 = t4+t23;
t25 = 1.0./sqrt(t24);
dCdp_heur = [W_t.*t10.*(b+2.0)+W_f.*t2.*t10.*wmax;W_f.*(((rx.*t15.*t20.*2.0+ry.*t15.*t21.*2.0+rz.*t15.*t22.*2.0).*1.0./sqrt(t20.^2+t21.^2+t22.^2))./2.0-t2.*t11.*wmax-alpha.*t3.*t10.^3.*t16.*t25.*pi.*2.0+1.0)-W_t.*(t11.*(b.*2.0+b.^2./2.0+1.0./2.0)+t11./t15);W_f.*(pi-t4.*t9.*wandamax.*1.3e+1+alpha.*t3.*t11.*t14.*t25.*pi.*(ka./2.0+1.0).*2.0)-W_t.*alpha.*t9.*(1.3e+1./2.0)];
