function d2Cdp2_heur = perform_cost_hess_heur(W,alpha,b,ka,kc,r,v,wandamax,wmax)
%PERFORM_COST_HESS_HEUR
%    D2CDP2_HEUR = PERFORM_COST_HESS_HEUR(W_F,W_T,ALPHA,B,KA,KC,RX,RY,RZ,VX,VY,VZ,WANDAMAX,WMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    13-Sep-2021 23:00:26

W_t = W(1);
W_f = W(2);

rx = r(1);
ry = r(2);
rz = r(3);

vx = v(1);
vy = v(2);
vz = v(3);

t2 = exp(b);
t3 = alpha.*wmax;
t4 = alpha.^2;
t6 = b+2.0;
t7 = ka.^2;
t8 = rx.^2;
t9 = ry.^2;
t10 = rz.^2;
t11 = 1.0./ka.^3;
t12 = 1.0./kc;
t17 = ka./2.0;
t5 = t4.^2;
t13 = t12.^2;
t14 = t12.^3;
t16 = t12.^5;
t18 = t17+1.0;
t19 = t7./4.0;
t23 = t8+t9+t10;
t15 = t13.^2;
t20 = W_t.*t6.*t13;
t21 = t18.^2;
t22 = W_f.*t2.*t13.*wmax;
t26 = 1.0./t23;
t27 = ka+t3+t19+1.0./4.0;
t28 = 1.0./sqrt(t23);
t24 = -t20;
t25 = -t22;
t29 = t27.^2;
t30 = t27.^3;
t31 = kc.*rx.*t28;
t32 = kc.*ry.*t28;
t33 = kc.*rz.*t28;
t34 = t31+vx;
t35 = t32+vy;
t36 = t33+vz;
t40 = t24+t25;
t41 = t4.*t13.*t29;
t37 = t34.^2;
t38 = t35.^2;
t39 = t36.^2;
t42 = t4+t41;
t43 = 1.0./sqrt(t42);
t46 = t37+t38+t39;
t44 = t43.^3;
t45 = alpha.*t3.*t14.*t18.*t27.*t43.*pi.*4.0;
t47 = alpha.^3.*t3.*t16.*t18.*t30.*t44.*pi.*2.0;
t48 = -t47;
t49 = t45+t48;
t50 = W_f.*t49;
t51 = -t50;
d2Cdp2_heur = reshape([W_t.*t12+W_f.*t2.*t12.*wmax,t40,0.0,t40,W_f.*(1.0./t46.^(3.0./2.0).*(rx.*t28.*t34.*2.0+ry.*t28.*t35.*2.0+rz.*t28.*t36.*2.0).^2.*(-1.0./4.0)+(1.0./sqrt(t46).*(t8.*t26.*2.0+t9.*t26.*2.0+t10.*t26.*2.0))./2.0+t2.*t14.*wmax.*2.0+alpha.*t3.*t15.*t29.*t43.*pi.*6.0-alpha.^3.*t3.*t13.^3.*t29.^2.*t44.*pi.*2.0)+W_t.*(t14.*(b.*2.0+b.^2./2.0+1.0./2.0).*2.0+(t14.*2.0)./t28),t51,0.0,t51,W_f.*(t4.*t11.*wandamax.*2.6e+1+alpha.*t3.*t13.*t21.*t43.*pi.*2.0+alpha.*t3.*t13.*t27.*t43.*pi-alpha.^3.*t3.*t15.*t21.*t29.*t44.*pi.*2.0)+W_t.*alpha.*t11.*1.3e+1],[3,3]);
